apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funbot-art
  namespace: funbot
  labels:
    app: funbot
    component: art
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
